### ISSUE TITLE
table prefix duplication

### ISSUE THREAD

**Issue by dayanstef** [Xethron/migrations-generator#87] opened 2016-09-30 10:17 UTC
When generating migrations from existing database with table prefix example: **prefix_**tablename - it stores the schema along with the table prefixes. Afterwords when you run php artisan migrate - it uses the prefix from configuration and adds additional prefixes example: **prefix_**prefix_tablename

I have a workaround with renaming the migrations and removing the prefixes from the table names so when I run the migrate command it adds the prefix configured in database config file.

You should consider eliminating the prefix based on the one configured in database config file and generating migration without prefixes if set

**Comment by Xethron** [comment] 2016-10-26 08:06
I remember this being added. There might be a bug with it... Will check it out

**Comment by Xethron** [comment] 2016-11-20 14:38
#22 appears to be an attempt to fix it. I believe it still has a few problems. Please check it out and let me know :) Thanks

**Comment by Xethron** [comment] 2016-11-20 14:44
This seems to be a duplicate of #22, closing this one as duplicate

**Closed by Xethron** 2016-11-20 14:44 UTC
Labels: Bug, Easy, Help Wanted
