### ISSUE TITLE
/dev/null/vcs does not exist and could not be created.

### ISSUE THREAD

**Issue by lijinma** [Xethron/migrations-generator#80] opened 2016-09-12 09:12 UTC
Using commands as follow will fix the issue:

    composer config repositories.repo-name vcs "git@github.com:jamisonvalenta/Laravel-4-Generators.git"

The type is `vcs` but not `git`

**Comment by Xethron** [comment] 2016-10-26 08:15
Hello @lijinma, will have to test it out. Thanks for reporting this!

**Comment by Xethron** [comment] 2016-10-27 11:23
Confirmed. Closing this one as a duplicate of #73

**Closed by Xethron** 2016-10-27 11:23 UTC
Labels: Bug, duplicate, Easy
